# Default configuration file
app:
  name: "Banking System"
  version: "1.0.0"
  environment: "development"
  mode: "debug"  # debug, release, test

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60

database:
  driver: "sqlite"
  dsn: "banking.db?_journal_mode=WAL"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300
  log_level: "info"

logging:
  level: "debug"
  format: "json"
  output: "stdout"
  file_path: "logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 7

security:
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expiry: 60
  bcrypt_cost: 10
  rate_limit: 100
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  trusted_proxies:
    - "127.0.0.1"
  enable_csrf: false
  enable_security_headers: true

features:
  enable_swagger: true
  enable_metrics: true
  enable_profiling: true
  maintenance_mode: false
  debug_mode: true